###FIND ALL

GET http://localhost:8080/flightgeneric/all

###ADD

POST http://localhost:8080/flightgeneric/add
Content-Type: application/json

{
  "departureAirport" : {
    "code" : "CDG"
  },
  "arrivalAirport" : {
    "code" : "CMN"
  },
  "departureHour" : "13:05",
  "arrivalHour" : "15:15",
  "basePrice" : 1326.00,
  "day" : {
    "code" : "SAT"
  },
  "plane" : {
    "id" : "bfbbfb83-d801-4c96-8f62-5b14217dafbf"
  },
  "departureTerminal" : {
    "code" : "CDG-2E"
  },
  "arrivalTerminal" : {
    "code" : "CMN-2"
  }
}

###FIND BY ID

GET http://localhost:8080/flightgeneric/find/205c83b4-9e1f-47ad-b3f1-e756c76f4bf0

###UPDATE

PUT http://localhost:8080/flightgeneric/update
Content-Type: application/json

{
  "id" : "08b212c7-fdc1-4031-8dee-4b16e7c2bedc",
  "departureAirport" : {
    "code" : "CMN"
  },
  "arrivalAirport" : {
    "code" : "ORY"
  },
  "departureHour" : "08:10",
  "arrivalHour" : "11:05",
  "basePrice" : 1700.00,
  "day" : {
    "code" : "SUN"
  },
  "plane" : {
    "id" : "2ac85539-683a-4393-87e6-b24e31bb8edb"
  },
  "departureTerminal" : {
    "code" : "CMN-1"
  },
  "arrivalTerminal" : {
    "code" : "ORY-4"
  }
}

###DELETE

DELETE http://localhost:8080/flightgeneric/delete/a95d4531-4297-4c8c-98e2-94c651b1d7f7